#!/usr/bin/env python
"""
Test: Verify SeekPath returns k-path in original hexagonal cell
"""
import numpy as np
from ase.io import read
from ase.cell import Cell

# Import patch to activate it
from TB2J.seekpath_patch import set_structure_context

# Read structure
atoms = read('/Users/vinicius/Documents/cifs/Gd.cif')
cell = atoms.get_cell()
positions_frac = atoms.get_scaled_positions()
atomic_numbers = atoms.get_atomic_numbers()

print("=" * 80)
print("TEST: SeekPath with HEXAGONAL CELL TRANSFORMATION")
print("=" * 80)

print(f"\nOriginal hexagonal cell:")
print(cell)

print(f"\nAtomic structure:")
print(f"  Positions (fractional): {positions_frac}")
print(f"  Atomic numbers: {atomic_numbers}")

# Generate bandpath with context
with set_structure_context(cell, positions_frac, atomic_numbers):
    bp = Cell(cell).bandpath(npoints=50)

print(f"\n### k-path Generated by SeekPath (HEXAGONAL) ###")
print(f"\nSpecial points (in ORIGINAL HEXAGONAL k-space):")
for name, coord in bp.special_points.items():
    print(f"  {name}: {coord}")

print(f"\nPath structure (.path):")
# Get from internal knames
knames = getattr(bp, '_knames', [])
if knames:
    print(f"  Segment labels: {' → '.join(knames)}")
    
    # Reconstruct path from knames
    segments = []
    for i in range(len(knames) - 1):
        if knames[i] != knames[i + 1]:
            segments.append(f"{knames[i]} → {knames[i + 1]}")
    print(f"  Segments: {', '.join(set(segments))}")

print(f"\nK-points array shape: {bp.kpts.shape}")
print(f"First 5 k-points:")
for i in range(min(5, len(bp.kpts))):
    print(f"  {bp.kpts[i]}")

print(f"\nLast 5 k-points:")
for i in range(max(0, len(bp.kpts) - 5), len(bp.kpts)):
    print(f"  {bp.kpts[i]}")

print(f"\n### Band structure plot axis ###")
x, Xs, knames_plot = bp.get_linear_kpoint_axis()
print(f"x range: {x[0]:.4f} to {x[-1]:.4f}")
print(f"Xs (special point positions on x-axis): {Xs}")
print(f"knames (special point labels): {knames_plot}")
