#!/usr/bin/env python3
import argparse
import ast

from TB2J.plot import plot_magnon_band, write_eigen
from TB2J.versioninfo import print_license

"""
The script to plot the magnon band structure.
"""


def plot_magnon():
    print_license()
    parser = argparse.ArgumentParser(
        description="TB2J_magnon: Plot magnon band structure from the TB2J magnetic interaction parameters"
    )
    parser.add_argument(
        "--fname",
        default="exchange.xml",
        type=str,
        help="exchange xml file name. default: exchange.xml",
    )

    parser.add_argument(
        "--qpath",
        default=None,
        type=str,
        help='The k-point path as space-separated or comma-separated names, e.g., "Gamma X P N" or "Gamma, X, P, N". If not given, the path will be automatically chosen using SeekPath.',
    )

    parser.add_argument(
        "--figfname",
        default=None,
        type=str,
        help="The file name of the figure. It should be e.g. png, pdf or other types of files which could be generated by matplotlib.",
    )

    parser.add_argument(
        "--Jq",
        action="store_true",
        help="To plot the eigenvalues of -J(q) instead of the magnon band",
        default=False,
    )

    parser.add_argument(
        "--no_Jiso",
        action="store_true",
        help="switch off isotropic exchange",
        default=None,
    )

    parser.add_argument(
        "--no_dmi", action="store_true", help="switch off dmi", default=None
    )

    parser.add_argument(
        "--no_Jani",
        action="store_true",
        help="switch off anisotropic exchange",
        default=None,
    )

    parser.add_argument(
        "--write_emin", action="store_true", help="switch to write emin", default=False
    )

    parser.add_argument(
        "--show",
        action="store_true",
        help="whether to show magnon band structure.",
        default=False,
    )

    args = parser.parse_args()
    if args.Jq:
        if args.figfname is None:
            args.figfname = "Eigen_Jq.pdf"
        print(
            "Plotting the eigenvalues of -J(q). The figure is written to %s"
            % (args.figfname)
        )
    else:
        if args.figfname is None:
            args.figfname = "magnon_band.pdf"
        print(
            "Plotting the magnon band structure. The figure is written to %s"
            % (args.figfname)
        )

    def nonone(x):
        if x is None:
            return x
        else:
            return not x

    # Parse custom k-point path if provided
    custom_kpoint_names = None
    if args.qpath is not None:
        try:
            # Try ast.literal_eval first (for properly quoted lists)
            try:
                custom_kpoint_names = ast.literal_eval(args.qpath)
            except (ValueError, SyntaxError):
                # Fallback: try comma-separated
                if ',' in args.qpath:
                    custom_kpoint_names = [n.strip().strip('"\'') for n in args.qpath.split(',')]
                else:
                    # Fallback: try space-separated
                    custom_kpoint_names = [n.strip().strip('"\'') for n in args.qpath.split()]
            
            if not isinstance(custom_kpoint_names, list):
                raise ValueError("--qpath must be a list")
            if not custom_kpoint_names:
                raise ValueError("--qpath list cannot be empty")
        except (ValueError, SyntaxError) as e:
            print(f"Error parsing --qpath: {e}")
            print('Expected format: --qpath "Gamma X P N" or --qpath "Gamma, X, P, N" or --qpath "[Gamma, X, P, N]"')
            import sys
            sys.exit(1)

    if args.write_emin:
        write_eigen(
            has_exchange=nonone(args.no_Jiso),
            has_dmi=nonone(args.no_dmi),
            has_bilinear=nonone(args.no_Jani),
        )
    else:
        plot_magnon_band(
            fname=args.fname,
            custom_kpoint_names=custom_kpoint_names,
            npoints=300,
            Jq=args.Jq,
            figfname=args.figfname,
            show=args.show,
            has_exchange=nonone(args.no_Jiso),
            has_dmi=nonone(args.no_dmi),
            has_bilinear=nonone(args.no_Jani),
        )


if __name__ == "__main__":
    plot_magnon()
